### ISSUE TITLE
node-gyp build fail

### ISSUE THREAD

**Issue by kevinian** [0xfeedface/node_raptor#12]
Hello,

I had used your module for couples of month, so far almost all works. I just a found a little bug, in some cases, the serializer misses the last character of localized literal. I do not know why. I use the version 0.1.0-2. 
The statement which need to be serialized:

``` json
{ 
  subject: 
   { type: 'uri',
     value: 'http://xxx.com/texts/a_md5_hash_could_not_be_evaluated_for_the_given_file' } ,
  predicate: { type: 'uri', value: 'http://schema.org/text' }, 
  object: 
   { lang: 'de',
     type: 'literal',
     value: 'Für die angegebene Datei konnte kein Md5 Hash evaluiert werden' }
}
```

The result:

```
<http://xxx.com/texts/a_md5_hash_could_not_be_evaluated_for_the_given_file> <http://schema.org/text> "F\u00FCr die angegebene Datei konnte kein Md5 Hash evaluiert werde"@de .
```

Today, I found you have a new version committed. However I can not install it by using node-gyp, many error occurs.
e.g., 

``` bash
../src/statement.h:25:22: error: expected ‘,’ or ‘...’ before ‘&&’ token
../src/statement.h:25:24: error: invalid constructor; you probably meant ‘Statement (const Statement&)’
../src/statement.h:28:33: error: expected ‘,’ or ‘...’ before ‘&&’ token
../src/parser.h:35:11: error: ‘function’ in namespace ‘std’ does not name a type
../src/parser.h:45:28: error: ‘statement_handler_t’ has not been declared
../src/parser.h:46:28: error: ‘namespace_handler_t’ has not been declared
../src/parser.h:47:26: error: ‘message_handler_t’ has not been declared
../src/parser.h:55:17: error: ‘class Parser’ has no member named ‘statementHandler_’
```

How can I install the new version? Can you tell me or update the README.md?
If you commit the module in the npm in the future, it will be absolutely great.

Best regards,
Kevin

**Comment by 0xfeedface** [comment]
I fixed the build script and tested it under Ubuntu 13.04. If it still doesn't work, you might need to install gcc 4.8 or clang.
